### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by Fornost461** [shoes/shoes3#392]
Hello, I ran the installer [Shoes 3.3.4 for Linux 64 bit](https://shoes.mvmanila.com/public/shoes/shoes-3.3.4-gtk3-x86_64.install) that I got from the [downloads page](http://shoesrb.com/downloads/). The install seemed successful, but when I later tried to run the file `~/.shoes/walkabout/shoes`, I got the following message:

>  ~/.shoes/walkabout/shoes-bin: error while loading shared libraries: libgif.so.4: cannot open shared object file: No such file or directory

I noticed that the `walkabout` folder had a file named `libgif.so.4.1.6`, so I made a link to it named `libgif.so.4`, and now Shoes seems to work.

**Comment by ccoupe** [comment]
I'm glad you got it working and thanks for reporting the bug. Which linux distro are you using?

**Comment by ccoupe** [comment]
@Fornost461, I've got a Shoes 3.3.5 [beta](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.5-gtk3-x86_64.install) for Linux 64 that has sym links for all the included libraries, just in case they trip you up later.  Should you care to to try it you'll have to un-install (from the menu,  if you have them) Not in your menus? `rm -rf ~/.shoes/walkabout/*` and then install the beta (anything new in 3.3.5 won't cause a problem since you don't know whats new with it so you can't try the new stuff which is undocumented. Risk free because Shoes only lives in  per user(~)  locations.

**Comment by Fornost461** [comment]
I am using Arch Linux. I installed the beta, thank you! (Is there an upgrade system, though? Do I have to check the project's page regularly to see if a new version is up?)

**Comment by BackOrder** [comment]
> (Is there an upgrade system, though? Do I have to check the project's page regularly to see if a new version is up?)

Hi @Fornost461, glad to meet you. We do not have an upgrade system at the moment. It would be really nice but we are tiny-tiny team. We explored the possibility with QtIFW #331. You are welcomed to contribute on anything or everything. :) :) :)

**Comment by Fornost461** [comment]
Hi @BackOrder ! I am a new Ruby newbie, so I may not contribute much codewise right now. I thought that upgrades are an important thing to mention, so I edited the wiki.

**Comment by BackOrder** [comment]
Coding is not the only way to contribute. Reporting issues, writing documentation, testing things around, feedback, etc. are meaningful contributions. We recently created a [Facebook page](https://www.facebook.com/TinyGraphicsToolkit/) aka #380.

What kind of projects are you interested in doing in Shoes?

**Comment by ccoupe** [comment]
Do I have to check the project's page regularly to see if a new version is up? Releases are mentioned on the mailling list and my blog.  There's no particular schedule - when enough new things are added plus bugfixs  and it seems like a long time since the last release (3 to 6 months).

If you watch the traffic here at github  you'll know about the betas which can change frequently depending on which git branch is being worked on and in this case to fix a problem. 

This is a 'it doesn't work issue so it needs to be fixed asap and known as 3.3.4 to replace what is there.

**Comment by Fornost461** [comment]
> What kind of projects are you interested in doing in Shoes?
I would like to make an organizational assistant.

> Releases are mentioned on the mailling list and my blog.
Ok, thanks!

**Comment by ccoupe** [comment]
Closing.

**Comment by zipizap** [comment]
Also happening with **shoes-3.3.5-gtk3-armhf.install**

After installing it will not start and if launched from command-line will show

> pi@raspberrypi:~/.shoes/walkabout $ ./shoes
> /home/pi/.shoes/walkabout/shoes-bin:  error while loading shared libraries: libgif.so.4: cannot open shared object file: No such file or directory


Workaround/solution: after installing shoes, run: 
`ln -s ~/.shoes/walkabout/libgif.so.4{.1.6,}`

And it will then work

**Comment by ccoupe** [comment]
Damn, I thought I fixed that. I must have skipped the pi. Thanks for reporting.

**Comment by ccoupe** [comment]
@zipizap  you might be better served by using the Shoes 3.3.6[ beta for rpi.](https://walkabout.mvmanila.com/public/shoes/shoes-3.3.6-gtk3-armhf.install) It fixes the symlinks to all the libraries.

**Comment by zipizap** [comment]
Many thanks Cecil for the quick answer - for the meantime I'll try with the
current version, as this is just a hobby project with very little time for
it :)
Thanks

**Comment by ccoupe** [comment]
You know what to do when jpeg, svg or yaml throws an exception . Gif (png) just happens to be used at start up. you can trigger the others working with Manual->Furthermore->Sample

**Comment by zipizap** [comment]
Ok, thanks for the heads-up

Ill have it into account
