### ISSUE TITLE
No Access to Binaries

### ISSUE THREAD

**Issue by ShadowfeindX** [shoes/shoes3#406]
Not sure if this is the appropriate place to put this, but I have been trying to download the binaries for shoes for some time now and I can't access the mvmanila website at all. It always times out. I've tried 3 browsers and curl with no luck, and as far as I can tell the binaries aren't hosted anywhere else. Is there some other way that I can download shoes? (specifically windows version for me)

**Comment by ccoupe** [comment]
Someone or something must be blocking mvmanila.com from you. I'm the owner of that site and it does go down occasionally but looking at yesterdays logs shows 20+ downloads.  It is possible mvmanila.com is on some anti-virus blacklist somewhere so you may have to turn your AV off or allow mvmanila.com

**Comment by ShadowfeindX** [comment]
I tested with both AV & Firewall on and off and I'm not behind a proxy of any kind. Are the binaries not hosted anywhere else? Is there any reason they aren't available as releases from the repo itself?

**Comment by ccoupe** [comment]
The way Shoes packaging works, they have to be hosted on a website that allows cgi scripts which github doesn't allow. I do know they've been copied by bot downloaders, aka unauthorized 'mirrors' so you might find those with a google search.  That said, your problem is pretty unique and intriguing. I just uploaded a beta to mvmanila.com and it's working for me.

**Comment by ccoupe** [comment]
Did you get it working?
